
    - name: Get nodejs setup script
      get_url: url=https://deb.nodesource.com/setup_6.x dest=~/nodejs-installer
      become: yes
      tags:
      - nodejs
      - run

    - name: Setup nodejs
      command: /bin/bash ~/nodejs-installer
      become: yes
      tags:
      - nodejs
      - run

    - name: Install nodejs
      apt: pkg=nodejs
      become: yes
      tags:
      - nodejs
      - run

    - name: Install git source control
      apt: pkg=git-core
      become: yes
      tags:
      - nodejs
      - development

    - name: Install vim plugins
      git: repo=https://github.com/pangloss/vim-javascript.git dest=~/.vim/bundle/vim-javascript
      tags:
      - nodejs
      - development
